<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Authors>ea-financial</Authors>
    <RepositoryUrl>https://tradeone.ghe.com/ea-financial/config-transform</RepositoryUrl>
  </PropertyGroup>
</Project>
